//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DESPACHO1 = new HashSet<DESPACHO>();
            this.PEDIDO1 = new HashSet<PEDIDO>();
        }
    
        public decimal ID_BOLETA { get; set; }
        public Nullable<decimal> DESCUENTOS { get; set; }
        public Nullable<decimal> TOTAL_FINAL { get; set; }
        public string TIPO_PAGO { get; set; }
        public Nullable<decimal> PROPINA { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
        public decimal DESPACHO_ID_DESPACHO { get; set; }
    
        public virtual DESPACHO DESPACHO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual ICollection<DESPACHO> DESPACHO1 { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO1 { get; set; }
    }
}
