//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.COMUNA = new HashSet<COMUNA>();
        }
    
        public decimal ID_CIUDAD { get; set; }
        public string NOMBRE_CIU { get; set; }
        public decimal PROVINCIA_ID_PROVINCIA { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual ICollection<COMUNA> COMUNA { get; set; }
    }
}
