//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public string RUN { get; set; }
        public string DIRECCION2 { get; set; }
        public string VALIDADO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
