//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public decimal ID_COMUNA { get; set; }
        public string NOMBRE_COM { get; set; }
        public string PERSONA_RUN { get; set; }
        public decimal CIUDAD_ID_CIUDAD { get; set; }
        public decimal CIUDAD_ID_PROVINCIA { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
