//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPACHO
    {
        public DESPACHO()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public decimal ID_DESPACHO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string OBSERVACIONES { get; set; }
        public decimal BOLETA_ID_BOLETA { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual BOLETA BOLETA1 { get; set; }
    }
}
