//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public string DETALLE_PRODUCTO { get; set; }
        public decimal DETALLE_CANTIDAD { get; set; }
        public decimal DETALLE_TOTAL { get; set; }
        public decimal ID_DETALLE { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
