//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID_MENU { get; set; }
        public string PRODUCTO1 { get; set; }
        public string PRODUCTO2 { get; set; }
        public string PRODUCTO3 { get; set; }
        public string PRODUCTO4 { get; set; }
        public string PRODUCTO5 { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
