//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOM_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public decimal MENU_ID_MENU { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
