//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public PROVINCIA()
        {
            this.CIUDAD = new HashSet<CIUDAD>();
        }
    
        public decimal ID_PROVINCIA { get; set; }
        public string NOMBRE_PRO { get; set; }
    
        public virtual ICollection<CIUDAD> CIUDAD { get; set; }
    }
}
